services:
  - type: web
    name: your-web-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://sartor:RkfESDHALVWw7ZNQ@fabstore.l8ispzm.mongodb.net/sartorial?retryWrites=true&w=majority&appName=FabStore
