services:
  - type: web
    name: sartorial-master
    env: node
    plan: free
    buildCommand: 'npm run client-build'
    startCommand: 'npm start'
    envVars:
      - key: PORT
        value: 8000
      - key: MONGO_URI
        value: mongodb+srv://sartor:RkfESDHALVWw7ZNQ@fabstore.l8ispzm.mongodb.net/sartorial?retryWrites=true&w=majority&appName=FabStore
